=== mineralsprings/json-api-host/schemas/autogen/menu.schema.json
{
    "$schema": "http://json-schema.org/draft-03/schema#", 
    "required": true, 
    "type": "object", 
    "id": "#", 
    "properties": {
        "item_list": {
            "items": {
                "required": true, 
                "type": "object", 
                "id": "0", 
                "properties": {
                    "comment": {
                        "required": true, 
                        "type": "string", 
                        "id": "comment"
                    }, 
                    "fullname": {
                        "required": true, 
                        "type": "string", 
                        "id": "fullname"
                    }, 
                    "sort_id": {
                        "required": true, 
                        "type": "number", 
                        "id": "sort_id"
                    }, 
                    "price": {
                        "required": true, 
                        "type": "number", 
                        "id": "price"
                    }, 
                    "options": {
                        "required": true, 
                        "type": "object", 
                        "id": "options", 
                        "properties": {
                            "add bacon bits": {
                                "required": true, 
                                "type": "number", 
                                "id": "add bacon bits"
                            }
                        }
                    }
                }
            }, 
            "required": true, 
            "type": "array", 
            "id": "item_list"
        }, 
        "expires": {
            "required": true, 
            "type": "number", 
            "id": "expires"
        }, 
        "is_buffet": {
            "required": true, 
            "type": "boolean", 
            "id": "is_buffet"
        }, 
        "effective": {
            "required": true, 
            "type": "number", 
            "id": "effective"
        }
    }
}

=== mineralsprings/json-api-host/json/menu.json
{
  "is_buffet": false,
  "effective": 4524452454,
  "expires": 124325512342,
  "item_list": [
    {
      "fullname": "Chicken Soup",
      "price": 1.3,
      "comment": "Homestyle and cheap, what more could you want?",
      "sort_id": 1,
      "options": {
        "add bacon bits": 0.5
      }
    },
    {
      "fullname": "Pizza",
      "price": 4.5,
      "comment": "American Grease",
      "sort_id": 2,
      "options": {
        "add sosig": 0.5
      }
    }
  ]
}
